import { getSession } from 'next-auth/client'
import Head from 'next/head'
import Banner from './components/Banner'
import Header from './components/Header'
import ProductFeed from './components/ProductFeed'


export default function Home({products}) {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>Amazon Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Center section */}
      <main className='max-w-screen-2xl mx-auto'>

        {/* Banner */}
        <Banner />

        {/* Product feed */}
        <ProductFeed products={products} />
      </main>

    </div>
  )
}

// Server Side Rendering
export async function getServerSideProps(context) {
  const session = await getSession(context);
  const products = await fetch('https://fakestoreapi.com/products')
    .then(res => res.json());

  return {
    props: {
      products,        // (or) products: products.results
      session
    }
  }
}
